logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    root: WARN
spring:
  data:
    mongodb:
      database: dev
      uri: mongodb://localhost:27017/dev
server:
  port: 8080