logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    root: WARN
spring:
  data:
    mongodb:
      uri: mongodb+srv://collector:4KdzC2AjqVozZ1aJ@cluster0-ghsgi.mongodb.net/dev
server:
  port: 8080